name = "carbon-api-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "carbon-api-worker"

[[d1_databases]]
binding = "DB"
database_name = "carbon-projects-db"
database_id = "your-database-id"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "carbon-project-files"

[vars]
JWT_SECRET = "your-jwt-secret-key"
OPENAI_API_KEY = "your-openai-api-key"