name = "carbon-auth-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "carbon-auth-worker"

[[d1_databases]]
binding = "DB"
database_name = "carbon-projects-db"
database_id = "your-database-id"

[vars]
JWT_SECRET = "your-jwt-secret-key"