name = "carbon-api-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "carbon-api-worker"

[[d1_databases]]
binding = "DB"
database_name = "carbon-projects-db"
database_id = "35e8e4ea-9cc6-4fc0-8451-9a75f9ea539d"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "carbon-project-files"
